### ISSUE TITLE
Hacktoberfest repository

### ISSUE THREAD

**Issue by frclba** [shiffman/Twitter-Bot-A2Z#1]
Hey Daniel @shiffman  !!!

I'm looking for repositories to contribute for the 2020 hacktoberfest event. 
Please make this one eligible by adding the tag hacktoberfest-accepted and describing ways we can contribute to. 

Thanks in advance. You are appreciated anyways.

https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by shiffman** [comment]
added!
